### ISSUE TITLE
baseline value doesn't work on headers

### ISSUE THREAD

**Issue by Marcel-Brouette** [xmendez/wfuzz#188]
It seems that the base line value doesn't work on header fuzzing : 

### 1- this command works well : 
` wfuzz -w headers.payloads -H "FUZZ: admin" --hc=200 https://url.com/`
### 2- This command says that the FUZZ word is missing: 
` wfuzz -w headers.payloads -H "FUZZ{notthere}: admin" --hc=BBB https://url.com/`
==> 
`Fatal exception: You must specify at least a FUZZ word!`
### 3- When I add an additionnal FUZZ word in url, it get the baseline value from the '-H' option and doesn't add any header but fuzz correctly the URL ....
`wfuzz -w headers.payloads -H "FUZZ{notthere}: admin" --hc=BBB -p 127.0.0.1:8080 https://url.com/FUZZ`

Request from the local proxy :  

```
GET /notthere HTTP/1.1
Host: url.com
Accept: */*
Content-Type: application/x-www-form-urlencoded
User-Agent: Wfuzz/2.4
Connection: close
```

Wfuzz version: 2.4.5
Python version: 2.7.17
OS: Kali rolling

**Comment by xmendez** [comment]
Hi,

This has been fixed in dev version at https://github.com/xmendez/wfuzz/commit/55db4f33b2ff7bce5907643797f4fe0c1d29b582
and it'll merge to master eventually.

`$ ./wfuzz -z list --zD test -H "FUZZ{baseline_value}: admin" -u http://www.google.com --efield r
********************************************************
* Wfuzz 3.0.0 - The Web Fuzzer                         *
********************************************************

Target: http://www.google.com/
Total requests: 1

===================================================================
ID           Response   Lines    Word     Chars       Payload                                                                                                                                                                                                                    
===================================================================

000000001:   200        10 L     331 W    13071 Ch    "baseline_value | GET / HTTP/1.1                                                                                                                                                                                           
                                                      Content-Type: application/x-www-form-urlencoded                                                                                                                                                                            
                                                      User-Agent: Wfuzz/3.0.0                                                                                                                                                                                                    
                                                      Host: www.google.com                                                                                                                                                                                                       
                                                      baseline_value: admin                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                 
                                                      "                                                                                                                                                                                                                          
000000000:   200        10 L     331 W    13160 Ch    "test | GET / HTTP/1.1                                                                                                                                                                                                     
                                                      Content-Type: application/x-www-form-urlencoded                                                                                                                                                                            
                                                      User-Agent: Wfuzz/3.0.0                                                                                                                                                                                                    
                                                      Host: www.google.com                                                                                                                                                                                                       
                                                      test: admin                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                 
                                                      "         `

cheers
