### ISSUE TITLE
hc doesn't work when changing size of pane in tmux 

### ISSUE THREAD

**Issue by rsmith31415** [xmendez/wfuzz#35]
I noticed a small issue when brute forcing directories with wfuzz in tmux. If you set the flag `hc` to hide certain type of responses, this works okay until you resize the tmux pane. Let me show it in steps:

0. To give a bit of context, this is the initial layout in tmux.

![screenshot from 2017-01-02 17-25-36](https://cloud.githubusercontent.com/assets/599274/21597445/807abd8c-d110-11e6-81e6-693c93301486.png)

1. You launch wfuzz in some pane with the `hc` flag. Here I "maximized" the pane.

![screenshot from 2017-01-02 17-10-52](https://cloud.githubusercontent.com/assets/599274/21597338/122f1c7a-d10f-11e6-8247-eee3057a603d.png)

2. Then you resize the pane (this screenshot only shows a part of the 4x4 layout). This is done by pressing `prefix+Z`. By default, `prefix` means `Ctrl+B`  in tmux. 

![screenshot from 2017-01-02 17-11-06](https://cloud.githubusercontent.com/assets/599274/21597359/651b2a50-d10f-11e6-8e29-04eeb01d9582.png)

3. Now you go back to the initial layout (again pressing `prefix+Z`) 

![screenshot from 2017-01-02 17-11-16](https://cloud.githubusercontent.com/assets/599274/21597373/9f79f42e-d10f-11e6-9d06-87fed9673905.png)

As you can see, when there are changes in the layout, the flag `hc` doesn't work anymore. Let me know if you need help reproducing these steps.

**Comment by xmendez** [comment]
This is a known issue. Because the width of the screen, the special characters used to erase the line do not work correctly. I plan to migrate to curses at some point in the future.

**Comment by rsmith31415** [comment]
That would be great. Thank you very much.

**Comment by lukapusic** [comment]
I look forward to the solution. This also happens when resizing Terminal in Mac OS.

**Comment by Prinzhorn** [comment]
I assume this is related, I'm having the same issue once the payload is too large for a single line. As you can see in the screenshot once the payload is 73 characters it doesn't fit and the line is not filtered even though it is 404.

![selection_395](https://user-images.githubusercontent.com/679144/49005739-bd05ce80-f167-11e8-9e53-16a8b86c27de.png)

**Comment by xmendez** [comment]
Yes, it is the same bug.

**Comment by Prinzhorn** [comment]
> This is a known issue. Because the width of the screen, the special characters used to erase the line do not work correctly. I plan to migrate to curses at some point in the future.

This seems to be a common issue with more than one duplicate. Is there anything you can do without migrating everything to curses? I know too little about python and terminal escape codes. Is there a way to not wrap the lines? Or to clear multiple lines if you know they've been wrapped? Maybe by inserting a marker to know how far you have to clear? Or add an option like the opposite of -v which will not show the payload at all. This would also solve another issue for me, because [some fuzzing lists](https://github.com/danielmiessler/SecLists/blob/f9c1ec678c1cae461f1dc8b654ceb6719fd03d33/Fuzzing/big-list-of-naughty-strings.txt#L677) will contain escape codes and wfuzz outputs them as-is without proper escaping.

Anyway, a workaround would be to not show the contents of the "payload" column until the request is done and filtering has happened. This way I can still watch progress in real time and only if the payload becomes relevant (e.g. because it is not 404) I can see it.

**Comment by xmendez** [comment]
Until this is fixed, you can use another printer as a workaround
ie. wfuzz -o raw -w xxx http:/xxxx

**Comment by xmendez** [comment]
Please, check if this issue has been addressed in Wfuzz 2.4.
