### ISSUE TITLE
Cannot add request body for PUT requests

### ISSUE THREAD

**Issue by vingtsyl** [xmendez/wfuzz#86]
Hi,

I am using wfuzz 2.3 for REST API testing. I have an issue with PUT request. Similarly to POST request, I am using -d parameter to set a request body but when the request is sent, the request body is empty. 
Exemple:
wfuzz -X PUT -v -d "{\"mybody\":\"FUZZ\"}"  -z file,wordlist.txt https://myrestapi/update

Seems to be fixed by pull request: https://github.com/xmendez/wfuzz/pull/85

**Comment by xmendez** [comment]
Hi,

Although the 2.3 code is in master branch, Wfuzz 2.3 has not been released yet. This is due to some last minute detected errors.

The aforementioned pull request breaks other unit and acceptance tests. This has been fixed in commit 769bef36bdca0e5157187b9d50688eb8bec86d7f

Could you please confirm if it works for you?

Cheers

**Comment by vingtsyl** [comment]
Yes it works now. Thank you
